title: chanceify™
description: A small, fast, private Spotify player for Windows. Built with love by chance.
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
  - _reference
  - _data
  - _includes
  - assets
