source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "webrick", "~> 1.9"
gem "jekyll-vitepress-theme"

# Keep links to guides published under the previous app name working.
gem "jekyll-redirect-from", "~> 0.16"
