//! Chanceify's internals, exposed so diagnostics and tests can reach them.

pub mod audio_shared;
pub mod analysis;
pub mod app_icons;
pub mod api;
pub mod app;
#[cfg(target_os = "linux")]
pub mod appearance;
pub mod auth;
pub mod autoscroll;
pub mod backend;
pub mod bidi;
pub mod beat;
pub mod bpm;
pub mod discord;
pub mod genres;
pub mod build_info;
pub mod crash;
pub mod cleanup;
pub mod credentials;
#[cfg(any(test, feature = "demo"))]
pub mod demo;
pub mod emoji;
pub mod exportify;
pub mod file_deck;
pub mod eq;
pub mod history;
pub mod http;
pub mod i18n;
pub mod images;
pub mod inspect;
pub mod lastfm;
pub mod lastfm_art;
pub mod local_match;
pub mod library_cache;
pub mod liked;
pub mod local_library;
pub mod limiter;
pub mod link;
pub mod lyrics;
#[cfg(target_os = "macos")]
pub mod mac_links;
#[cfg(target_os = "macos")]
pub mod mac_menu;
#[cfg(target_os = "macos")]
pub mod mac_touchbar_crash_guard;
pub mod media;
#[cfg(target_os = "linux")]
#[path = "mpris.rs"]
pub mod media_controls;
#[cfg(not(target_os = "linux"))]
#[path = "media_native.rs"]
pub mod media_controls;
pub mod membership;
pub mod model;
pub mod opener;
pub mod paths;
pub mod player;
pub mod playlist_cover;
pub mod releases;
pub mod resample;
pub mod response_cache;
pub mod scenes;
pub mod session_reads;
pub mod settings;
pub mod single_instance;
pub mod sink;
pub mod smart_shuffle;
pub mod speed;
pub mod stats;
pub mod swirl_art;
pub mod system_fonts;
pub mod theme;
pub mod tour;
pub mod thumbbar;
pub mod ui;
pub mod unavailable;
pub mod updates;
pub mod util;
pub mod vis;
pub mod window;
pub mod zeroconf;
